// netlify.toml - Netlify configuration for Next.js
[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PRIVATE_TARGET = "server"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Form notifications
[[notifications]]
  type = "email"
  event = "submission_created"
  email = "karlis.uproof@gmail.com"
